version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - myNetwork
  be:
    container_name: be
    build:
      context: ./
    image: nhathd/web-flux-server
    depends_on:
      - db
    ports:
      - 8082:8082
    environment:
      MQ_HOST: r2dbc:postgresql://db:5432/postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    networks:
      - myNetwork
  fe:
    container_name: fe
    build:
      context: ./
      target: production
    image: nhathd/vue-edition
    depends_on:
      - be
    ports:
      - 5173:5173
    environment:
      NODE_ENV: production
      VITE_BASE_URL: http://ip172-18-0-43-ckk13bufml8g00djju50-8082.direct.labs.play-with-docker.com/api
    links:
      - be
    volumes:
      - ./:/src
      - /src/node_modules
    networks:
      - myNetwork
volumes:
  db:
    driver: local
networks:
  myNetwork:
    driver: bridge
