version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - myNetwork
  api:
    container_name: web-flux-server
    build:
      context: ./
    image: nhathd/web-flux-server
    depends_on:
      - db
    ports:
      - 8082:8082
    environment:
      MQ_HOST: r2dbc:postgresql://db:5432/postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    networks:
      - myNetwork
volumes:
  db:
    driver: local
networks:
  myNetwork:
    driver: bridge
